
## INPUT FILES ##

# List of variant(s) to be tested. A.k.a. the "snplist".
# It should be a tab-separated file with the following columns: ID, Chrom, Pos, OA, EA
variant_file: "/home/antton/Projects/MM_GWAS/data/raw/snplist.txt"
  #"/home/antton/Projects/CordBlood_GWAS/transcription_factor_lookup/snplist.txt"

# ReMap metadata BED file. Remember it needs to be bgzipped and tabix indexed!
remap_data_file: "/home/antton/Tiny_Projects/ReMap_ChIP-seq_metadata_pipeline/data/remap2022_all_macs2_hg38_v1_0.bed.gz"

# hg38 reference genome fasta file
hg38_fa_file: "/media/antton/cbio3/projects/Zain_2021/hg38FASTA/hg38.fa"


## OUTPUT FILES ##

# TSV file with the studies with TFs that overlap the variant
remap_tmp_output_dir: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/tmp/remap_lookup_outputs/"
remap_output_file: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/output/remap_lookup_output.tsv"

# FABIAN-variant output files
fabian_output_data: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/output/FABIAN_OUTPUT_data.tsv"
fabian_output_table: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/output/FABIAN_OUTPUT_table.tsv"

# Output file with the overlapping TFs for each variant
output_file: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/variants_and_tfs.txt"

## OTHER PARAMETERS ##

tmp_folder: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/tmp/"

output_folder: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/output/"

samtools: "/home/antton/Programs/samtools-1.17/samtools"

# Biotypes used to filter the ReMap database data
#filters_str: "lymphocyte_blood blood_cord CD34_ERYTH_BMP K-562 Raji Namalwa OCI-Ly1 OCI-Ly1_JQ1 OCI-Ly3 OCI-Ly7 OCI-Ly19 BJAB BJAB_1h-activation BJAB_4h-activation SU-DHL-4 SU-DHL-5 SU-DHL-6"
filter_file: "/home/antton/Projects/MM_GWAS/transcription_factor_lookup/tmp/TMP_remap_lymphoid_overlap.tsv"
# TODO: the biotype filtering should be systematic instead of arbitrary. We can use the CCLE lymphoid cell list, and maybe
# add the blood related tissues. It will be easier to read the biotyoes from a file instead of listing them here!!