# Path to project directory. The pipeline will create several subfolders here.
global_project_dir: '/home/antton/Projects/Immune_GWAS/'

# Path to 'variant info' file
var_info_folder: '/media/antton/cbio3/data/BloodVariome_Taravero_preliminary_GWAS_2022-10-29/'

# Path to gzipped GWAS output files. These will be first copied to the project folder and subsequently decompressed.
gwas_data_folder: '/media/antton/cbio3/data/BloodVariome_Taravero_preliminary_GWAS_2022-10-29/'

# Name of the GWAS run the data originates from. This name will be used to create subfolders in the project folder.
name_of_gwas_run: 'BloodVariome_Taravero_preliminary_GWAS_2022-10-29'

# General type of the phenotype. E.g. 'Frequency_and_Ratio' or 'MFI'. This will be used to create sub-subfolders.
trait_type: 'MFI'  # 'Frequency_and_Ratio'

# P-value threshold to use for filtering GWAS results
pval_thresh: 1e-6
