import numpy as np
import os

configfile: "config.yaml"

config['pval_thresh'] = float(config['pval_thresh'])  # '1e-4' is read as a string, so we need to convert it to float


rule all:
    input:
        [config['intermediate_data_dir'] + '_'.join(gwas_file.rstrip('.txt').split('_')[4:-3]) + '.txt' for gwas_file in os.listdir(config['gwas_gzip_folder'])[:2]]


# TODO: Copy the 'variant_info_extended.txt' file as well so that we don't need to read it from cbio3. Will need to change the config file too.
rule copy_and_unzip_gwas_files:
    input:
        config['gwas_gzip_folder'] + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res.gz'
    params:
         bare_copy =config['raw_data_dir'] + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res.gz'
    output:
        config['raw_data_dir'] + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res'
    shell:
        'cp {input} {params.bare_copy}; gunzip {params.bare_copy}'


rule extract_significant_variants:
    input:
        config['var_info_folder'] + "variant_info_extended.txt",
        config['raw_data_dir']
    params:
        pval = -np.log10(config['pval_thresh']),
        output_dir = config['intermediate_data_dir'][:-1]
    output:
        config['intermediate_data_dir'] + '{phenotype}.txt'
    shell:
        "python extract_variants_by_pval.py {input} -p {params.pval} -o {params.output_dir}"


rule generate_template_manhattan:
    input:
        config['var_info_folder'] + "variant_info_extended.txt",
        config['raw_data_dir']
    params:
        output_dir = config['intermediate_data_dir'][:-1]
    output:
        config['intermediate_data_dir'] + 'template_manhattan.txt'
    shell:
        "python produce_full_sumstats_for_single_trait.py {input} -o {params.output_dir}"