import numpy as np
import os

configfile: "config.yaml"


# Initialize directory structure
if 'data' not in os.listdir(config['global_project_dir']):
    os.mkdir(config['global_project_dir'] + '/data')
if 'raw' not in os.listdir(config['global_project_dir'] + '/data'):
    os.mkdir(config['global_project_dir'] + '/data/raw')
if 'intermediate' not in os.listdir(config['global_project_dir'] + '/data'):
    os.mkdir(config['global_project_dir'] + '/data/intermediate')
if 'processed' not in os.listdir(config['global_project_dir'] + '/data'):
    os.mkdir(config['global_project_dir'] + '/data/processed')

# Create run-specific directories
if config['name_of_gwas_run'] not in os.listdir(config['global_project_dir'] + '/data/raw'):
    os.mkdir(config['global_project_dir'] + '/data/raw/' + config['name_of_gwas_run'])
if config['name_of_gwas_run'] not in os.listdir(config['global_project_dir'] + '/data/intermediate'):
    os.mkdir(config['global_project_dir'] + '/data/intermediate/' + config['name_of_gwas_run'])
if config['name_of_gwas_run'] not in os.listdir(config['global_project_dir'] + '/data/processed'):
    os.mkdir(config['global_project_dir'] + '/data/processed/' + config['name_of_gwas_run'])

# Global path variables
raw_data_dir = config['global_project_dir'] + 'data/raw/' + config['name_of_gwas_run'] + '/Frequency_and_Ratio/'
intermediate_data_dir = config['global_project_dir'] + 'data/intermediate/' + config['name_of_gwas_run'] + '/Frequency_and_Ratio/'


config['pval_thresh'] = float(config['pval_thresh'])  # '1e-4' is read as a string, so we need to convert it to float


rule all:
    input:
        [intermediate_data_dir + '_'.join(gwas_file.rstrip('.txt').split('_')[4:-3]) + '.txt' for gwas_file in os.listdir(config['gwas_gzip_folder'])[:2]]


# TODO: Copy the 'variant_info_extended.txt' file as well so that we don't need to read it from cbio3. Will need to change the config file too.
rule copy_and_unzip_gwas_files:
    input:
        config['gwas_gzip_folder'] + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res.gz'
    params:
         bare_copy = raw_data_dir + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res.gz'
    output:
        raw_data_dir + 'SWE_Swedes_Blood_variome_{phenotype}_adjSexPhaCohPC_InvNorm_12102022.res'
    shell:
        'cp {input} {params.bare_copy}; gunzip {params.bare_copy}'


rule extract_significant_variants:
    input:
        config['var_info_folder'] + "variant_info_extended.txt",
        raw_data_dir
    params:
        pval = -np.log10(config['pval_thresh']),
        output_dir = intermediate_data_dir[:-1]
    output:
        intermediate_data_dir + '{phenotype}.txt'
    shell:
        "python extract_variants_by_pval.py {input} -p {params.pval} -o {params.output_dir}"


rule generate_template_manhattan:
    input:
        config['var_info_folder'] + "variant_info_extended.txt",
        raw_data_dir
    params:
        output_dir = intermediate_data_dir[:-1]
    output:
        intermediate_data_dir + 'template_manhattan.txt'
    shell:
        "python produce_full_sumstats_for_single_trait.py {input} -o {params.output_dir}"
